# PlayerVaults Configuration File

# Number of slots per vault (must be a multiple of 9: 9, 18, 27, 36, 45, 54)
vault-size: 27

# Maximum number of vaults a player can have
max-vaults: 99

# Enable or disable admin access to all player vaults
allow-admin-access: true

# Should empty vaults be removed from vaults.yml to save space?
remove-empty-vaults: true

# Messages customization
messages:
  no-permission: "&cYou do not have permission to open this vault!"
  invalid-number: "&cInvalid vault number! Choose between 1-99."
  vault-open: "&aOpening Vault #%vault%..."
  admin-vault-open: "&aOpening %player%'s Vault #%vault%..."
  player-not-found: "&cThat player is not online!"
  only-players: "&cOnly players can use this command!"
  incorrect-usage: "&cUsage: /pv <1-99> OR /pv <player> <1-99>"

# Enable debugging messages in the console?
debug-mode: false